on:
  pull_request:
  push:

# Dorny test reporter needs these permissions.
permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3    
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test
        # In real case this should not be allowed, but now when we are not going to change current code implementations this add is needed so that reports are made.
        continue-on-error: true 

      - name: Test Report
        uses: dorny/test-reporter@v1
        continue-on-error: true # In real case remove this (see below the reason).
        if: success() || failure()    
        with:
          name: JEST Test Report          
          path: reports/jest-*.xml   
          reporter: jest-junit

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{secrets.COVERALLS_REPO_TOKEN}}
          path-to-lcov: ./coverage/lcov.info